---
title: "analysis on fallopian tubes"
author: "Chih-Hsuan Wu"
output: html_document
---
```{r, setup, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
source("../code/hippo_all_proportion.R")
source("../code/DE_methods.R")
source("../code/functions_in_rmd.R")
load("../data/fallopian_tubes.RData")

library(ggplot2)
library(dplyr)
library(MASS)
library(DESeq2)
library(MAST)
library(MuMIn)
library(Hmisc)
library(Seurat)
library(muscat)
library(sctransform)
library(SingleCellExperiment)
```

```{r}
# vstcounts = vst(counts(inputData), verbosity = FALSE)$y
# assays(inputData)$cpm = edgeR::cpm(counts(inputData))
# save(vstcounts, file = "../data/vstcounts.RData")
# load("../data/vstcounts.RData")
```

# Run DE methods on tube data
```{r}
pois_glmm_df = list()
binom_glmm_df = list()
MAST_donor_df = list()
Wilcox_Seurat_integrated_df = list()
Wilcox_Seurat_normlized_df = list()
DESeq2.muscat = list()
edgeR.cpm = list()
MMvst = list() 
MMpoisson = list()

pair = list(c(2,19), c(8,17), c(12,13), list(c(8,17), c(2,19)), c(12,19))
for(i in 1:length(pair)){
  assign_subgroup(unlist(pair[[i]][1]), unlist(pair[[i]][2]))
  # poisson_glmm
  pois_glmm_df[[cur_key]] = poisson_glmm_DE(subgroupsce, comparison = "hippo_cluster", replicates = "donor")
  pois_glmm_df[[cur_key]]$hits = identifyDEGs(pois_glmm_df[[cur_key]]$BH, pois_glmm_df[[cur_key]]$log2FC, subgroupsce@metadata$log2mean, subgroupsce@metadata$log2meandiff, log2FCcutoff = log2(1.5))

  # binom_glmm
  binom_glmm_df[[cur_key]] = binomial_glmm_DE(subgroupsce, comparison = "hippo_cluster", replicates = "donor")
  binom_glmm_df[[cur_key]]$hits = identifyDEGs(binom_glmm_df[[cur_key]]$BH, binom_glmm_df[[cur_key]]$log2FC, subgroupsce@metadata$log2mean, subgroupsce@metadata$log2meandiff, log2FCcutoff = log2(1.5), newcriteria = T)

  
  # MAST
  MAST_donor_df[[cur_key]] = MAST_DE(subgroupsce, cellgroup, subgroupsce$donor)
  MAST_donor_df[[cur_key]]$hits = identifyDEGs(MAST_donor_df[[cur_key]]$BH, MAST_donor_df[[cur_key]]$log2FC, log2FCcutoff = log2(1.5), newcriteria = F)
  
  
  # Seurat_Wilcox_integrated
  Wilcox_Seurat_integrated_df[[cur_key]] = FindMarkers(subgroup_Seurat, ident.1 = as.character(group1), ident.2 = as.character(group2), test.use = "wilcox", assay = "integrated")
  Wilcox_Seurat_integrated_df[[cur_key]]$genes = rownames(Wilcox_Seurat_integrated_df[[cur_key]])
  Wilcox_Seurat_integrated_df[[cur_key]]$hits = identifyDEGs(Wilcox_Seurat_integrated_df[[cur_key]]$p_val_adj, Wilcox_Seurat_integrated_df[[cur_key]]$avg_log2FC, log2FCcutoff = log2(1.5), newcriteria = F)
  
  # Seurat_Wilcox_normalized
  Wilcox_Seurat_normlized_df[[cur_key]] = FindMarkers(subgroup_Seurat, ident.1 = as.character(group1), ident.2 = as.character(group2), test.use = "wilcox", assay = "RNA")
  Wilcox_Seurat_normlized_df[[cur_key]]$genes = rownames(Wilcox_Seurat_normlized_df[[cur_key]])
  Wilcox_Seurat_normlized_df[[cur_key]]$hits = identifyDEGs(Wilcox_Seurat_normlized_df[[cur_key]]$p_val_adj, Wilcox_Seurat_normlized_df[[cur_key]]$avg_log2FC, log2FCcutoff = log2(1.5), newcriteria = F)
  
  

  subgroupsce$cluster_id = "void"
  subgroupsce$group_id = factor(paste0("hippo",sapply(subgroupsce$hippo_cluster,                                        function(x){ifelse(x%in% group1, paste0(group1, collapse = "_"), paste0(group2, collapse = "_"))})), levels = paste0("hippo",c(paste0(group1, collapse = "_"), paste0(group2, collapse = "_"))))


  subgroupsce$sample_id = as.factor(paste0(subgroupsce$group_id, subgroupsce$donor))
  subgroupsce = prepSCE(subgroupsce,
                      kid = "cluster_id",
                      gid = "group_id",
                      sid = "sample_id",
                      drop = FALSE)
    # DESeq2.muscat
  pb = aggregateData(subgroupsce,
    assay = "counts", fun = "sum",
    by = c("cluster_id", "sample_id"))
  res = pbDS(pb, method = "DESeq2", verbose = F)
  DESeq2.muscat[[cur_key]] = data.frame(res$table[[1]][[1]])[,c(1,4,7,8)]
  DESeq2.muscat[[cur_key]]$logFC = log2(exp(DESeq2.muscat[[cur_key]]$logFC))
  colnames(DESeq2.muscat[[cur_key]]) = c("genes", "log2FC", "pval", "BH")
  DESeq2.muscat[[cur_key]]$hits = identifyDEGs(DESeq2.muscat[[cur_key]]$BH, DESeq2.muscat[[cur_key]]$log2FC, log2FCcutoff = log2(1.5), newcriteria = F)

  # edgeR.sum.cpm
  pb = aggregateData(subgroupsce,
    assay = "cpm", fun = "sum",
    by = c("cluster_id", "sample_id"))
  res = pbDS(pb, method = "edgeR", verbose = FALSE)
  edgeR.cpm[[cur_key]] = data.frame(res$table[[1]][[1]])[,c(1,3,6,7)]
  edgeR.cpm[[cur_key]]$logFC = log2(exp(edgeR.cpm[[cur_key]]$logFC))
  colnames(edgeR.cpm[[cur_key]])[1:4] = c("genes", "log2FC", "pval", "BH")
  edgeR.cpm[[cur_key]]$hits = identifyDEGs(edgeR.cpm[[cur_key]]$BH, edgeR.cpm[[cur_key]]$log2FC, log2FCcutoff = log2(1.5), newcriteria = F)


  # MM-vst
  subgroupsce_vst = subgroupsce[rownames(subgroupsce) %in% rownames(vstcounts),]
  assays(subgroupsce_vst)$vstresiduals = vstcounts[, colnames(vstcounts)%in% colnames(subgroupsce_vst)]
  res = mmDS(subgroupsce_vst, method = "vst", vst = "sctransform")
  MMvst[[cur_key]] = data.frame(res[[1]])[,c(1,3,6,7)]
  MMvst[[cur_key]]$beta = log2(exp(MMvst[[cur_key]]$beta))
  colnames(MMvst[[cur_key]])[1:4] = c("genes", "log2FC", "pval", "BH")
  MMvst[[cur_key]]$hits = identifyDEGs(MMvst[[cur_key]]$BH, MMvst[[cur_key]]$log2FC, log2FCcutoff = log2(1.5), newcriteria = F)

  # MM-poisson
  res = mmDS(subgroupsce, method = "poisson")
  MMpoisson[[cur_key]] = data.frame(res[[1]])[,c(1,3,6,7)]
  MMpoisson[[cur_key]]$beta = log2(exp(MMpoisson[[cur_key]]$beta))
  colnames(MMpoisson[[cur_key]])[1:4] = c("genes", "log2FC", "pval", "BH")
  MMpoisson[[cur_key]]$hits = identifyDEGs(MMpoisson[[cur_key]]$BH,                                    MMpoisson[[cur_key]]$log2FC, log2FCcutoff = log2(1.5), newcriteria = F)
}
```

```{r}
save(pois_glmm_df, binom_glmm_df, MAST_donor_df, Wilcox_Seurat_integrated_df, Wilcox_Seurat_normlized_df, DESeq2.muscat, edgeR.cpm, MMvst, MMpoisson,file = "../data/10X_DEresult_update2.RData")
```
