---
title: "W/WO library size factor"
author: "Chih-Hsuan Wu"
output: html_document
---
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---
```{r, setup, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```

```{r, eval = FALSE}
source("./code/DE_methods.R")
source("./code/functions_in_rmd.R")
load("./data/fallopian_tubes.RData")
load("./data/fallopian_DEresult.RData")

```

```{r, eval = FALSE}
results = list()
sizefactor_ratio = list()
```

```{r, eval = FALSE}
pair = list(c(12,13), c(8,17), c(2,19), c(12,19))

for (i in 1:length(pair)){
  assign_subgroup(unlist(pair[[i]][1]), unlist(pair[[i]][2]))
  
  group_sizefactor = aggregate(sizeFactor ~ hippo_cluster, data = data.frame(colData(subgroupsce)[,c("sizeFactor", "hippo_cluster"), drop = T]), FUN = mean, na.rm = TRUE)
  group_sizefactor = group_sizefactor[order(group_sizefactor$hippo_cluster),]
  sizefactor_ratio[[cur_key]] = log2(group_sizefactor[1,2]/group_sizefactor[2,2])
  
  results[[cur_key]][["w_offset"]] = poisson_glmm_DE(subgroupsce, comparison = "hippo_cluster", replicates = "donor", ls_offset = T)
  results[[cur_key]][["w_offset"]]$genemean = rowMeans(subgroupsce@assays@data$counts)

  results[[cur_key]][["wo_offset"]] = pois_glmm_df[[cur_key]]
}
```

```{r, eval = FALSE}
load("./data/Kang_data.RData")
load("./data/Kang_DEresult.RData")
assign_celltype("B cells")

group_sizefactor = aggregate(sizeFactor ~ group_id, data = data.frame(colData(subgroupsce)[,c("sizeFactor", "group_id"), drop = T]), FUN = mean, na.rm = TRUE)
  group_sizefactor = group_sizefactor[order(group_sizefactor$group_id),]
  sizefactor_ratio[[cur_key]] = log2(group_sizefactor[1,2]/group_sizefactor[2,2])
  
results[[cur_key]][["w_offset"]] = poisson_glmm_DE(subgroupsce, comparison = "group_id", replicates = "ind", exp_batch = "sample_id", ls_offset = T)
  results[[cur_key]][["w_offset"]]$genemean = rowMeans(subgroupsce@assays@data$counts)
  
  results[[cur_key]][["wo_offset"]] = Kang_pois_glmm_df[[cur_key]]
```

```{r, eval = FALSE}
load("./data/human_spine.RData")
load("./data/human_spine_DEresult.RData")
group1 = "Dors_Horn"
group2 = "Vent_Lat_White"
pair = c(group1, group2)
cur_key = paste(group1, group2, sep = " vs. ")
subgroupsce = sce_human_spine_filtered[, sce_human_spine_filtered$region%in%pair]

group_sizefactor = aggregate(sizeFactor ~ region, data = data.frame(colData(subgroupsce)[,c("sizeFactor", "region"), drop = T]), FUN = mean, na.rm = TRUE)
  group_sizefactor = group_sizefactor[order(group_sizefactor$region),]
  sizefactor_ratio[[cur_key]] = log2(group_sizefactor[1,2]/group_sizefactor[2,2])


results[[cur_key]][["w_offset"]] = poisson_glmm_DE(subgroupsce, comparison = "region", replicates = "patient_ID", exp_batch = "Slide", ls_offset = T)
  results[[cur_key]][["w_offset"]]$genemean = rowMeans(subgroupsce@assays@data$counts)
  
  results[[cur_key]][["wo_offset"]] = pois_glmm_df
```
```{r, eval = FALSE}
save(sizefactor_ratio, results, file = "../data/ls_offset_Result.RData")
```

```{r, fig.width=8}
load("./data/ls_offset_Result.RData")
library(ggplot2)
library(ggpubr)
library(reshape2)
pval_plots <- list()
FC_plots <- list()
for (comparison_name in names(results)) {
  
  pval_data <- data.frame(
    with_offset = results[[comparison_name]][["w_offset"]]$pval, 
    without_offset = results[[comparison_name]][["wo_offset"]]$pval,
    genemean = results[[comparison_name]][["w_offset"]]$genemean,
    log2FC = results[[comparison_name]][["wo_offset"]]$log2FC
  )
    FC_data <- data.frame(
    with_offset = results[[comparison_name]][["w_offset"]]$log2FC, 
    without_offset = results[[comparison_name]][["wo_offset"]]$log2FC,
    genemean = results[[comparison_name]][["w_offset"]]$genemean
  )
  
  # Create a scatter plot of p-values
p <- ggplot(pval_data, aes(x = without_offset, y = with_offset, color = log2FC)) +
    geom_point(alpha = 0.6) +
    geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "red") +  # Identity line for comparison
    labs(title = comparison_name,
         x = "Without Offset (p-value)",
         y = "With Offset (p-value)",
         color = "log2FC") +  # Add a color legend title
    theme_bw() + 
  theme(panel.grid = element_blank()) + 
    scale_color_gradient2(limits = c(-1.5,1.5), low = "red", mid = "#F6EFBD",
                            high = "blue")
  
  # Add the plot to the list
  pval_plots[[comparison_name]] <- p
  

# Reshape the data from wide to long format
FC_long <- melt(FC_data, measure.vars = c("with_offset", "without_offset"),
                  variable.name = "Offset_Type", value.name = "log2FC")

mean_log2FC = aggregate(log2FC ~ Offset_Type, data = FC_long, FUN = mean, na.rm = TRUE)
meanshift = mean_log2FC[1,2] - mean_log2FC[2,2]
annotate_line = data.frame(xintercept = c(meanshift, sizefactor_ratio[[comparison_name]]), color = c("Distribution Shift", "SizeFactor Ratio"))

p <- ggplot(FC_long, aes(x = log2FC, fill = Offset_Type)) +
  geom_histogram(alpha=0.5, position="identity", bins = 50) + 
  labs(title = comparison_name,
       x = "Log2 Fold Change",
       y = "Count") +
  xlim(c(-3,3)) + 
  ylim(c(0,1000)) +
  geom_vline(xintercept = 0, color = "black") +
  geom_vline(
    data = annotate_line,
    mapping = aes(xintercept = xintercept, color = color),
    linetype = "dashed"
  ) +
    theme_bw() + 
  theme(panel.grid = element_blank()) +
  scale_fill_discrete(guide = guide_legend(title = "Model"),labels = c("With offset", "Without offset")) +
  scale_color_manual(guide = guide_legend(title = ""),values = c("blue", "purple"))


  
  # Add the plot to the list
  FC_plots[[comparison_name]] <- p
}
ggarrange(plotlist = FC_plots, common.legend = T)
ggarrange(plotlist = pval_plots, common.legend = T)

```

